'use strict';

/**
 * Dados-base para popular o sistema de estudos ENEM.
 *
 * Tópicos e ranking de "mais cobrado" vêm da pesquisa: SAS Educação (Raio-X do
 * Enem 2009-2024), Aprova Total, CNN Brasil, Toda Matéria, Estratégia
 * Vestibulares, Querobolsa, Estuda.com (ago/2026).
 *
 * Cada aula carrega os campos "fonte" e "verificado" apenas para uso interno
 * do script (relatório de avisos) — eles NUNCA são enviados à API.
 *   - verificado:true  -> o link real foi conferido (URL existe e bate com o tema).
 *   - verificado:false -> o tópico é confirmadamente "mais cobrado" pelas fontes
 *     citadas, mas nenhum vídeo específico foi localizado ainda. A aula é
 *     cadastrada sem conteúdo (conteudos: []); "fonte" traz a string de busca
 *     sugerida para completar depois via PATCH /admin/aulas/{id}.
 *
 * Nenhum enunciado de questão real do INEP foi extraído nesta pesquisa (ela
 * cobriu só aulas/vídeos) — as questões abaixo continuam sendo modelos
 * autorais no estilo ENEM, não itens oficiais.
 */

const MATERIAS = [
  { nome: 'Matemática', area: 'matematica', icone: 'Calculator', cor: '#2563EB', descricao: 'Matemática e suas tecnologias' },
  { nome: 'Português', area: 'linguagens', icone: 'BookOpen', cor: '#16A34A', descricao: 'Linguagens, códigos e suas tecnologias' },
  { nome: 'Biologia', area: 'natureza', icone: 'Leaf', cor: '#059669', descricao: 'Ciências da natureza — Biologia' },
  { nome: 'Química', area: 'natureza', icone: 'FlaskConical', cor: '#7C3AED', descricao: 'Ciências da natureza — Química' },
  { nome: 'Física', area: 'natureza', icone: 'Atom', cor: '#DB2777', descricao: 'Ciências da natureza — Física' },
  { nome: 'História', area: 'humanas', icone: 'Landmark', cor: '#B45309', descricao: 'Ciências humanas — História' },
  { nome: 'Geografia', area: 'humanas', icone: 'Globe2', cor: '#0891B2', descricao: 'Ciências humanas — Geografia' },
  { nome: 'Redação', area: 'redacao', icone: 'PenLine', cor: '#DC2626', descricao: 'Redação dissertativo-argumentativa do ENEM' },
];

const TOPICOS = {
  'Matemática': [
    'Razão, proporção e regra de três',
    'Porcentagem',
    'Estatística básica (média, moda, mediana)',
    'Função afim (1º grau)',
    'Função quadrática (2º grau)',
    'Geometria plana (áreas e perímetros)',
    'Geometria espacial (volumes)',
    'Análise combinatória e probabilidade',
    'Progressões (PA e PG)',
  ],
  'Português': [
    'Interpretação de texto',
    'Funções da linguagem',
    'Variação linguística',
    'Figuras de linguagem',
    'Gêneros textuais',
    'Coesão e coerência textual',
    'Modernismo',
    'Literatura contemporânea',
    'Intertextualidade',
  ],
  'Biologia': [
    'Ecologia — conceitos e cadeias alimentares',
    'Ecossistemas',
    'Genética',
    'Evolução',
    'Fisiologia humana',
    'Citologia',
  ],
  'Química': [
    'Estequiometria',
    'Termoquímica',
    'Química orgânica — funções orgânicas',
    'Soluções e concentração',
    'Eletroquímica (pilhas)',
    'Cinética química',
    'Ligações químicas',
    'Química ambiental',
    'pH e equilíbrio químico',
    'Petróleo e polímeros',
  ],
  'Física': [
    'Cinemática (MU e MUV)',
    'Leis de Newton',
    'Energia mecânica e trabalho',
    'Eletrodinâmica (circuitos, potência elétrica)',
    'Eletrostática',
    'Hidrostática (Pascal, Arquimedes, Stevin)',
    'Termologia (calor, dilatação)',
    'Ondulatória',
    'Óptica',
    'Energia elétrica no cotidiano',
  ],
  'História': [
    'Escravidão no Brasil',
    'Período colonial',
    'Independência e Brasil Império',
    'Era Vargas',
    'Ditadura Militar e redemocratização',
    'Revolução Industrial',
    'Revolução Francesa',
    'Guerra Fria e Segunda Guerra Mundial',
    'Descolonização da África e diáspora africana',
    'Movimentos sociais e cidadania (séc. XX-XXI)',
  ],
  'Geografia': [
    'Globalização',
    'Geopolítica mundial',
    'Urbanização brasileira',
    'Mudanças climáticas e desmatamento',
    'Industrialização e agricultura brasileira',
    'Migrações',
    'Demografia e população',
    'Domínios morfoclimáticos do Brasil',
    'Questão agrária e concentração fundiária',
    'Comércio mundial e blocos econômicos',
  ],
  'Redação': [
    'As 5 competências da redação (visão geral)',
    'Competência 1 — norma culta da língua',
    'Competência 2 — compreensão do tema',
    'Competência 3 — argumentação',
    'Competência 4 — coesão textual',
    'Competência 5 — proposta de intervenção',
    'Estrutura dissertativo-argumentativa',
    'Repertório sociocultural',
    'Como escrever uma redação do zero',
    'Análise de redações nota 1000',
  ],
};

// Aula com vídeo real e conferido (URL checada — existe e bate com o tema).
function aulaVideo({ titulo, topico, resumo, duracao, dificuldade, mais_cobrado, fonte, video_link, descricao }) {
  return {
    titulo,
    topico,
    resumo,
    dificuldade: dificuldade || 'basico',
    mais_cobrado: !!mais_cobrado,
    fonte,
    verificado: true,
    conteudos: [
      {
        tipo: 'video',
        ordem: 0,
        duracao,
        ativo: true,
        titulo,
        video_link,
        descricao,
      },
    ],
  };
}

// Aula com conteúdo em texto, quando a fonte real é um artigo/página (não um vídeo solto).
function aulaTexto({ titulo, topico, resumo, dificuldade, mais_cobrado, fonte, descricao }) {
  return {
    titulo,
    topico,
    resumo,
    dificuldade: dificuldade || 'basico',
    mais_cobrado: !!mais_cobrado,
    fonte,
    verificado: true,
    conteudos: [
      {
        tipo: 'texto',
        ordem: 0,
        duracao: 300,
        ativo: true,
        titulo,
        descricao,
      },
    ],
  };
}

// Tópico confirmado como "mais cobrado" pelas fontes de frequência, mas sem
// vídeo específico ainda localizado — cadastra a aula sem conteúdo (a preencher depois).
function aulaPendente({ titulo, topico, resumo, dificuldade, mais_cobrado, fonte }) {
  return {
    titulo,
    topico,
    resumo,
    dificuldade: dificuldade || 'basico',
    mais_cobrado: !!mais_cobrado,
    fonte,
    verificado: false,
    conteudos: [],
  };
}

function questaoModelo({ topico, ano, dificuldade, enunciado, alternativas, dica, explicacao, fonte }) {
  return {
    topico,
    ano: ano ?? null,
    dificuldade: dificuldade || 'medio',
    enunciado,
    imagem_url: null,
    dica: dica || null,
    explicacao: explicacao || null,
    alternativas,
    fonte,
    verificado: false,
  };
}

const CONTEUDO = {
  'Matemática': {
    aulas: [
      aulaPendente({
        titulo: 'Razão, proporção e regra de três',
        topico: 'Razão, proporção e regra de três',
        resumo: 'Tópico nº1 em frequência no ENEM segundo o Raio-X SAS Educação (213 questões, 2009-2024).',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "Regra de três Khan Academy Brasil"',
      }),
      aulaPendente({
        titulo: 'Porcentagem',
        topico: 'Porcentagem',
        resumo: 'Aplicações de porcentagem em problemas contextualizados do ENEM.',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "Porcentagem Me Salva ENEM"',
      }),
      aulaPendente({
        titulo: 'Estatística básica (média, moda, mediana)',
        topico: 'Estatística básica (média, moda, mediana)',
        resumo: 'Tópico nº2 em frequência no ENEM segundo SAS Educação (187 questões).',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "Khan Academy estatística média moda mediana"',
      }),
      aulaVideo({
        titulo: 'Função quadrática (introdução)',
        topico: 'Função quadrática (2º grau)',
        resumo: 'Introdução à função do 2º grau na trilha de Álgebra do Khan Academy Brasil.',
        duracao: 600,
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'Khan Academy Brasil — trilha de Álgebra do Ensino Médio',
        video_link: 'https://pt.khanacademy.org/math/em-mat-algebra',
        descricao: 'Trilha de álgebra do Khan Academy Brasil, com o módulo de função quadrática.',
      }),
      aulaVideo({
        titulo: 'Função Quadrática no ENEM: Entenda Resolvendo 6 Questões',
        topico: 'Função quadrática (2º grau)',
        resumo: 'Resolução comentada de 6 questões de função quadrática que já caíram no ENEM.',
        duracao: 1200,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube (verificado 2026-08-19): "Função Quadrática no ENEM: Entenda Resolvendo 6 Questões"',
        video_link: 'https://www.youtube.com/watch?v=hj51vJWZZ-A',
        descricao: 'Vídeo-aula com 6 questões de função quadrática já cobradas no ENEM, resolvidas passo a passo.',
      }),
      aulaPendente({
        titulo: 'Geometria plana (áreas e perímetros)',
        topico: 'Geometria plana (áreas e perímetros)',
        resumo: 'Tópico nº3 em frequência no ENEM segundo SAS Educação (110 questões).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "geometria plana Khan Academy Brasil áreas"',
      }),
      aulaPendente({
        titulo: 'Geometria espacial (volumes)',
        topico: 'Geometria espacial (volumes)',
        resumo: 'Cálculo de volumes de sólidos geométricos em contextos do ENEM.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "geometria espacial ENEM volumes videoaula"',
      }),
      aulaPendente({
        titulo: 'Análise combinatória e probabilidade',
        topico: 'Análise combinatória e probabilidade',
        resumo: 'Contagem, arranjos, combinações e cálculo de probabilidade.',
        dificuldade: 'dificil',
        mais_cobrado: false,
        fonte: 'buscar: "análise combinatória probabilidade Me Salva ENEM"',
      }),
      aulaPendente({
        titulo: 'Progressões (PA e PG)',
        topico: 'Progressões (PA e PG)',
        resumo: 'Progressões aritméticas e geométricas aplicadas a problemas do ENEM.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "PA PG progressões Khan Academy"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Função afim (1º grau)',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'Uma empresa de transporte cobra uma taxa fixa de R$ 5,00 mais R$ 2,50 por quilômetro rodado. Qual é o valor pago por uma corrida de 12 km?',
        alternativas: [
          { letra: 'A', texto: 'R$ 25,00', correta: false },
          { letra: 'B', texto: 'R$ 30,00', correta: false },
          { letra: 'C', texto: 'R$ 35,00', correta: true },
          { letra: 'D', texto: 'R$ 40,00', correta: false },
          { letra: 'E', texto: 'R$ 45,00', correta: false },
        ],
        dica: 'Monte a função afim f(x) = taxa fixa + valor por km × x.',
        explicacao: 'f(12) = 5 + 2,5 × 12 = 5 + 30 = R$ 35,00.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Estatística básica (média, moda, mediana)',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'Em uma turma de 40 alunos, 25 foram aprovados em Matemática. Qual a porcentagem aproximada de aprovação?',
        alternativas: [
          { letra: 'A', texto: '52,5%', correta: false },
          { letra: 'B', texto: '62,5%', correta: true },
          { letra: 'C', texto: '65,0%', correta: false },
          { letra: 'D', texto: '72,5%', correta: false },
        ],
        dica: 'Divida o número de aprovados pelo total e multiplique por 100.',
        explicacao: '25/40 = 0,625 = 62,5%.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Português': {
    aulas: [
      aulaPendente({
        titulo: 'Interpretação de texto',
        topico: 'Interpretação de texto',
        resumo: 'Cerca de 60% da prova de Linguagens depende diretamente de interpretação de texto (SAE Digital / Toda Matéria).',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "interpretação de texto ENEM Curso Enem Gratuito"',
      }),
      aulaPendente({
        titulo: 'Funções da linguagem',
        topico: 'Funções da linguagem',
        resumo: 'Reconhecimento das seis funções da linguagem em textos do ENEM.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "funções da linguagem ENEM videoaula"',
      }),
      aulaPendente({
        titulo: 'Variação linguística',
        topico: 'Variação linguística',
        resumo: 'Registro formal x informal, regionalismos e preconceito linguístico.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "variação linguística ENEM Português"',
      }),
      aulaPendente({
        titulo: 'Figuras de linguagem',
        topico: 'Figuras de linguagem',
        resumo: 'Metáfora, metonímia, ironia e outras figuras cobradas em textos literários e publicitários.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "figuras de linguagem ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Gêneros textuais',
        topico: 'Gêneros textuais',
        resumo: 'Reconhecimento de gêneros (charge, notícia, crônica, poema, etc.) na prova de Linguagens.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "gêneros textuais ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Coesão e coerência textual',
        topico: 'Coesão e coerência textual',
        resumo: 'Conectivos e organização lógica do texto — base também para a Redação.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "coesão coerência ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Modernismo',
        topico: 'Modernismo',
        resumo: 'Movimento literário presente em 19,9% das questões de literatura do ENEM (Toda Matéria).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "modernismo brasileiro ENEM aula literatura"',
      }),
      aulaPendente({
        titulo: 'Literatura contemporânea',
        topico: 'Literatura contemporânea',
        resumo: 'Movimento mais cobrado em literatura no ENEM: 30,8% das questões (Toda Matéria).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "literatura contemporânea ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Intertextualidade',
        topico: 'Intertextualidade',
        resumo: 'Diálogo entre textos — paródia, paráfrase e referências culturais.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "intertextualidade ENEM aula"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Variação linguística',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'Um texto publicitário que usa gírias e expressões informais para se aproximar do público jovem exemplifica principalmente qual fenômeno linguístico?',
        alternativas: [
          { letra: 'A', texto: 'Variação linguística', correta: true },
          { letra: 'B', texto: 'Concordância verbal', correta: false },
          { letra: 'C', texto: 'Regência nominal', correta: false },
          { letra: 'D', texto: 'Coesão referencial', correta: false },
        ],
        dica: 'Pense em como a linguagem muda conforme o contexto social e o público-alvo.',
        explicacao: 'O uso de gírias conforme o público-alvo é um caso de variação linguística (registro informal).',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Interpretação de texto',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão.',
        alternativas: [
          { letra: 'A', texto: 'Fazem dois anos que ele se formou.', correta: false },
          { letra: 'B', texto: 'Faz dois anos que ele se formou.', correta: true },
          { letra: 'C', texto: 'Fazem dois anos que ele se formaram.', correta: false },
          { letra: 'D', texto: 'Faziam dois anos que ele se formou.', correta: false },
        ],
        dica: 'O verbo "fazer" indicando tempo decorrido é impessoal e fica na 3ª pessoa do singular.',
        explicacao: '"Fazer" com sentido de tempo transcorrido não flexiona: "Faz dois anos".',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Biologia': {
    aulas: [
      aulaVideo({
        titulo: 'Enem 2023 - Biologia - Aula 8 - Ecologia - Conceitos e Cadeias Alimentares',
        topico: 'Ecologia — conceitos e cadeias alimentares',
        resumo: 'Ecologia responde por cerca de 50% das questões de Biologia no ENEM (Prof. Paulo Jubilut).',
        duracao: 1500,
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'YouTube (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=_p9O7WoVyhw',
        descricao: 'Conceitos fundamentais de ecologia e cadeias alimentares para o ENEM.',
      }),
      aulaVideo({
        titulo: 'Como ECOLOGIA é cobrada no ENEM | Prof. Paulo Jubilut',
        topico: 'Ecologia — conceitos e cadeias alimentares',
        resumo: 'Análise de como a banca do ENEM cobra ecologia, com exemplos de questões.',
        duracao: 1080,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube — Prof. Paulo Jubilut (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=KKELP-3_Dlk',
        descricao: 'Como a ecologia costuma aparecer nas provas do ENEM.',
      }),
      aulaVideo({
        titulo: 'Tudo sobre Ecossistemas – Resumo de Biologia pro ENEM',
        topico: 'Ecossistemas',
        resumo: 'Resumo completo de ecossistemas para revisão do ENEM.',
        duracao: 900,
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'YouTube (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=wlAR_cifwOM',
        descricao: 'Resumo de tipos de ecossistemas e suas características.',
      }),
      aulaVideo({
        titulo: 'Introdução à Genética | Resumo de Biologia para o Enem',
        topico: 'Genética',
        resumo: 'Base de genética mendeliana para o ENEM.',
        duracao: 900,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=JsLH-x_tSZ0',
        descricao: 'Introdução aos conceitos de genética cobrados no ENEM.',
      }),
      aulaVideo({
        titulo: '7 questões de genética do Enem',
        topico: 'Genética',
        resumo: 'Resolução comentada de 7 questões reais de genética já cobradas no ENEM.',
        duracao: 1500,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube (verificado 2026-08-19): "7 questões de genética do Enem"',
        video_link: 'https://www.youtube.com/watch?v=WPMHKxC9Bg0',
        descricao: '7 questões de genética já cobradas no ENEM, resolvidas passo a passo.',
      }),
      aulaVideo({
        titulo: 'Genética (8/8): Evolução - Biologia - ENEM',
        topico: 'Evolução',
        resumo: 'Último módulo da série de genética, focado em evolução biológica.',
        duracao: 900,
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'YouTube (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=JmlI6bkigl8',
        descricao: 'Conceitos de evolução biológica cobrados no ENEM.',
      }),
      aulaVideo({
        titulo: 'Tudo sobre ECOLOGIA para o ENEM | Prof. Paulo Jubilut',
        topico: 'Ecologia — conceitos e cadeias alimentares',
        resumo: 'Aulão completo de ecologia cobrindo os principais pontos do ENEM.',
        duracao: 3600,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube — Prof. Paulo Jubilut (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/watch?v=Rr-zQYqRCzo',
        descricao: 'Aulão de revisão de ecologia para o ENEM.',
      }),
      aulaVideo({
        titulo: 'Genética | Biologia para o Enem (playlist)',
        topico: 'Genética',
        resumo: 'Playlist completa de genética para revisão do ENEM.',
        duracao: 3600,
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'YouTube — playlist (verificado 2026-08-19)',
        video_link: 'https://www.youtube.com/playlist?list=PLQVUQftDIJQFW2c1dqjTOjzOKxCTs6We8',
        descricao: 'Playlist completa cobrindo genética para o ENEM.',
      }),
      aulaPendente({
        titulo: 'Fisiologia humana',
        topico: 'Fisiologia humana',
        resumo: 'Sistemas do corpo humano cobrados no ENEM (digestório, circulatório, nervoso, etc.).',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "fisiologia humana ENEM Biologia Total"',
      }),
      aulaPendente({
        titulo: 'Citologia',
        topico: 'Citologia',
        resumo: 'Estrutura e função das células, organelas e membrana plasmática.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "citologia ENEM aula Biologia Total"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Ecologia — conceitos e cadeias alimentares',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'Em uma cadeia alimentar formada por capim, gafanhoto, sapo e cobra, o gafanhoto ocupa qual nível trófico?',
        alternativas: [
          { letra: 'A', texto: 'Produtor', correta: false },
          { letra: 'B', texto: 'Consumidor primário', correta: true },
          { letra: 'C', texto: 'Consumidor secundário', correta: false },
          { letra: 'D', texto: 'Decompositor', correta: false },
        ],
        dica: 'O consumidor primário é o que se alimenta diretamente do produtor.',
        explicacao: 'O gafanhoto se alimenta do capim (produtor), sendo consumidor primário.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Genética',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'No cruzamento entre dois indivíduos heterozigotos (Aa x Aa), qual a proporção fenotípica esperada na prole, considerando dominância completa?',
        alternativas: [
          { letra: 'A', texto: '1:1', correta: false },
          { letra: 'B', texto: '1:2:1', correta: false },
          { letra: 'C', texto: '3:1', correta: true },
          { letra: 'D', texto: '9:3:3:1', correta: false },
        ],
        dica: 'Monte o quadro de Punnett para Aa x Aa.',
        explicacao: 'Aa x Aa gera 1AA:2Aa:1aa, ou seja, 3 dominantes para 1 recessivo (3:1) no fenótipo.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Química': {
    aulas: [
      aulaPendente({
        titulo: 'Estequiometria',
        topico: 'Estequiometria',
        resumo: 'Físico-química + química geral + orgânica somam 75% da prova de Química (SAS Educação).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "estequiometria ENEM aula Química"',
      }),
      aulaPendente({
        titulo: 'Termoquímica',
        topico: 'Termoquímica',
        resumo: 'Calor de reação, entalpia e gráficos de energia.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "termoquímica ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Química orgânica — funções orgânicas',
        topico: 'Química orgânica — funções orgânicas',
        resumo: 'Reconhecimento de álcoois, ácidos carboxílicos, ésteres e outras funções.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "funções orgânicas ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Soluções e concentração',
        topico: 'Soluções e concentração',
        resumo: 'Concentração comum, molaridade e diluição em contextos do ENEM.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "soluções concentração ENEM Química aula"',
      }),
      aulaPendente({
        titulo: 'Eletroquímica (pilhas)',
        topico: 'Eletroquímica (pilhas)',
        resumo: 'Reações de oxirredução e funcionamento de pilhas.',
        dificuldade: 'dificil',
        mais_cobrado: false,
        fonte: 'buscar: "eletroquímica pilhas ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Cinética química',
        topico: 'Cinética química',
        resumo: 'Fatores que alteram a velocidade das reações químicas.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "cinética química ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Ligações químicas',
        topico: 'Ligações químicas',
        resumo: 'Ligações iônicas, covalentes e metálicas — base da química geral.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "ligações químicas ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Química ambiental',
        topico: 'Química ambiental',
        resumo: 'Poluição, efeito estufa e tratamento de água — muito ligado a temas de atualidades.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "química ambiental ENEM aula"',
      }),
      aulaPendente({
        titulo: 'pH e equilíbrio químico',
        topico: 'pH e equilíbrio químico',
        resumo: 'Escala de pH, ácidos, bases e deslocamento de equilíbrio.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "pH equilíbrio químico ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Petróleo e polímeros',
        topico: 'Petróleo e polímeros',
        resumo: 'Cadeia produtiva do petróleo e formação de polímeros — química orgânica aplicada.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "petróleo polímeros ENEM aula química orgânica"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Estequiometria',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'Qual a massa, em gramas, de 2 mols de água (H2O), considerando massas atômicas H = 1 e O = 16?',
        alternativas: [
          { letra: 'A', texto: '18 g', correta: false },
          { letra: 'B', texto: '36 g', correta: true },
          { letra: 'C', texto: '9 g', correta: false },
          { letra: 'D', texto: '54 g', correta: false },
        ],
        dica: 'Calcule a massa molar da água e multiplique pelo número de mols.',
        explicacao: 'Massa molar da água = 18 g/mol. Para 2 mols: 2 × 18 = 36 g.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Química orgânica — funções orgânicas',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'O etanol (CH3-CH2-OH), amplamente usado como combustível no Brasil, pertence a qual função orgânica?',
        alternativas: [
          { letra: 'A', texto: 'Ácido carboxílico', correta: false },
          { letra: 'B', texto: 'Éster', correta: false },
          { letra: 'C', texto: 'Álcool', correta: true },
          { letra: 'D', texto: 'Cetona', correta: false },
        ],
        dica: 'Observe a hidroxila (-OH) ligada a carbono saturado.',
        explicacao: 'A presença do grupo -OH em carbono saturado caracteriza a função álcool.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Física': {
    aulas: [
      aulaPendente({
        titulo: 'Cinemática (MU e MUV)',
        topico: 'Cinemática (MU e MUV)',
        resumo: 'Mecânica + eletricidade/energia somam 58,5% da prova de Física (SAS Educação).',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "cinemática ENEM aula Física"',
      }),
      aulaPendente({
        titulo: 'Leis de Newton',
        topico: 'Leis de Newton',
        resumo: 'Inércia, força resultante e ação-reação.',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "leis de Newton ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Energia mecânica e trabalho',
        topico: 'Energia mecânica e trabalho',
        resumo: 'Energia cinética, potencial e conservação de energia mecânica.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "energia mecânica trabalho ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Eletrodinâmica (circuitos, potência elétrica)',
        topico: 'Eletrodinâmica (circuitos, potência elétrica)',
        resumo: 'Circuitos em série/paralelo e cálculo de potência elétrica.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "eletrodinâmica circuitos ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Eletrostática',
        topico: 'Eletrostática',
        resumo: 'Cargas elétricas, campo elétrico e Lei de Coulomb.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "eletrostática ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Hidrostática (Pascal, Arquimedes, Stevin)',
        topico: 'Hidrostática (Pascal, Arquimedes, Stevin)',
        resumo: 'Pressão em fluidos e princípios de Pascal, Arquimedes e Stevin.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "hidrostática ENEM aula Pascal Arquimedes"',
      }),
      aulaPendente({
        titulo: 'Termologia (calor, dilatação)',
        topico: 'Termologia (calor, dilatação)',
        resumo: 'Calor sensível/latente, dilatação térmica e trocas de calor.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "termologia calor ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Ondulatória',
        topico: 'Ondulatória',
        resumo: 'Características das ondas: comprimento, frequência e velocidade.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "ondulatória ENEM aula física"',
      }),
      aulaPendente({
        titulo: 'Óptica',
        topico: 'Óptica',
        resumo: 'Reflexão, refração e formação de imagens em lentes e espelhos.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "óptica ENEM aula física"',
      }),
      aulaPendente({
        titulo: 'Energia elétrica no cotidiano',
        topico: 'Energia elétrica no cotidiano',
        resumo: 'Cálculo de consumo elétrico e leitura de contas de energia — tema recorrente e contextualizado.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "energia elétrica consumo ENEM aula"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Leis de Newton',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'Um corpo de massa 2 kg é acelerado a 3 m/s². Qual a força resultante que age sobre ele, segundo a 2ª Lei de Newton?',
        alternativas: [
          { letra: 'A', texto: '1 N', correta: false },
          { letra: 'B', texto: '3 N', correta: false },
          { letra: 'C', texto: '5 N', correta: false },
          { letra: 'D', texto: '6 N', correta: true },
        ],
        dica: 'Use F = m × a.',
        explicacao: 'F = 2 kg × 3 m/s² = 6 N.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Eletrodinâmica (circuitos, potência elétrica)',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'Em um circuito em série, o que acontece com a corrente elétrica ao longo do circuito?',
        alternativas: [
          { letra: 'A', texto: 'A corrente é a mesma em todos os pontos.', correta: true },
          { letra: 'B', texto: 'A corrente aumenta a cada resistor.', correta: false },
          { letra: 'C', texto: 'A corrente diminui a cada resistor.', correta: false },
          { letra: 'D', texto: 'A corrente é nula no circuito.', correta: false },
        ],
        dica: 'Em série, não há divisão de caminhos para a corrente.',
        explicacao: 'No circuito em série a corrente elétrica é igual em qualquer ponto, pois há um único caminho.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'História': {
    aulas: [
      aulaPendente({
        titulo: 'Escravidão no Brasil',
        topico: 'Escravidão no Brasil',
        resumo: 'Tema mais cobrado em História no ENEM (Toda Matéria / Querobolsa).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "escravidão Brasil ENEM aula história"',
      }),
      aulaPendente({
        titulo: 'Período colonial',
        topico: 'Período colonial',
        resumo: 'Colonização e expansão marítima portuguesa no Brasil.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "período colonial Brasil ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Independência e Brasil Império',
        topico: 'Independência e Brasil Império',
        resumo: 'Processo de independência e organização política do Brasil Império.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "Brasil Império independência ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Era Vargas',
        topico: 'Era Vargas',
        resumo: 'Governo Provisório, Constitucional e Estado Novo (1930-1945).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "Era Vargas ENEM aula história"',
      }),
      aulaPendente({
        titulo: 'Ditadura Militar e redemocratização',
        topico: 'Ditadura Militar e redemocratização',
        resumo: 'Regime militar brasileiro (1964-1985) e o processo de abertura política.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "ditadura militar ENEM aula história"',
      }),
      aulaPendente({
        titulo: 'Revolução Industrial',
        topico: 'Revolução Industrial',
        resumo: 'Transformações econômicas e sociais a partir da industrialização europeia.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "revolução industrial ENEM aula história"',
      }),
      aulaPendente({
        titulo: 'Revolução Francesa',
        topico: 'Revolução Francesa',
        resumo: 'Ideais iluministas e impacto na organização política moderna.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "revolução francesa ENEM aula história"',
      }),
      aulaPendente({
        titulo: 'Guerra Fria e Segunda Guerra Mundial',
        topico: 'Guerra Fria e Segunda Guerra Mundial',
        resumo: 'Bipolarização mundial e conflitos do século XX.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "guerra fria segunda guerra mundial ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Descolonização da África e diáspora africana',
        topico: 'Descolonização da África e diáspora africana',
        resumo: 'Processos de independência africana e sua relação com a diáspora e o Brasil.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "descolonização África diáspora ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Movimentos sociais e cidadania (séc. XX-XXI)',
        topico: 'Movimentos sociais e cidadania (séc. XX-XXI)',
        resumo: 'Movimentos por direitos civis, sociais e ambientais na história recente.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "movimentos sociais cidadania ENEM aula história"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Independência e Brasil Império',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'O grito do Ipiranga, marco simbólico da independência do Brasil, ocorreu em que ano?',
        alternativas: [
          { letra: 'A', texto: '1808', correta: false },
          { letra: 'B', texto: '1815', correta: false },
          { letra: 'C', texto: '1822', correta: true },
          { letra: 'D', texto: '1889', correta: false },
        ],
        dica: 'É o mesmo ano em que Dom Pedro I proclamou a independência.',
        explicacao: 'A independência do Brasil foi proclamada em 7 de setembro de 1822.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Era Vargas',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'A criação da CLT (Consolidação das Leis do Trabalho) está associada a qual período da história republicana brasileira?',
        alternativas: [
          { letra: 'A', texto: 'Primeira República (1889-1930)', correta: false },
          { letra: 'B', texto: 'Era Vargas (1930-1945)', correta: true },
          { letra: 'C', texto: 'Ditadura Militar (1964-1985)', correta: false },
          { letra: 'D', texto: 'Nova República (pós-1985)', correta: false },
        ],
        dica: 'Pense no governo que criou o Ministério do Trabalho e ampliou direitos trabalhistas.',
        explicacao: 'A CLT foi instituída em 1943, durante o Estado Novo, no governo de Getúlio Vargas.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Geografia': {
    aulas: [
      aulaPendente({
        titulo: 'Globalização',
        topico: 'Globalização',
        resumo: 'Integração econômica, cultural e tecnológica mundial.',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "globalização ENEM aula geografia"',
      }),
      aulaPendente({
        titulo: 'Geopolítica mundial',
        topico: 'Geopolítica mundial',
        resumo: 'Conflitos internacionais e blocos econômicos — um dos eixos mais fortes da prova (Estuda.com / Aprova Total).',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "geopolítica mundial ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Urbanização brasileira',
        topico: 'Urbanização brasileira',
        resumo: 'Êxodo rural, metropolização e desigualdades urbanas no Brasil.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "urbanização Brasil ENEM aula geografia"',
      }),
      aulaPendente({
        titulo: 'Mudanças climáticas e desmatamento',
        topico: 'Mudanças climáticas e desmatamento',
        resumo: 'Aquecimento global, desmatamento e sustentabilidade — tema recorrente em atualidades.',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "mudanças climáticas desmatamento ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Industrialização e agricultura brasileira',
        topico: 'Industrialização e agricultura brasileira',
        resumo: 'Formação industrial do Brasil e o agronegócio moderno.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "industrialização agricultura Brasil ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Migrações',
        topico: 'Migrações',
        resumo: 'Movimentos migratórios internos e internacionais e seus impactos sociais.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "migrações ENEM aula geografia"',
      }),
      aulaPendente({
        titulo: 'Demografia e população',
        topico: 'Demografia e população',
        resumo: 'Transição demográfica, pirâmides etárias e distribuição populacional.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar: "demografia população ENEM aula geografia"',
      }),
      aulaPendente({
        titulo: 'Domínios morfoclimáticos do Brasil',
        topico: 'Domínios morfoclimáticos do Brasil',
        resumo: 'Biomas e domínios climáticos brasileiros (Amazônia, Cerrado, Caatinga, etc.).',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "domínios morfoclimáticos Brasil ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Questão agrária e concentração fundiária',
        topico: 'Questão agrária e concentração fundiária',
        resumo: 'Estrutura fundiária brasileira e conflitos no campo.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "questão agrária concentração fundiária ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Comércio mundial e blocos econômicos',
        topico: 'Comércio mundial e blocos econômicos',
        resumo: 'Mercosul, União Europeia e outros blocos regionais no comércio internacional.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "comércio mundial blocos econômicos ENEM aula"',
      }),
    ],
    questoes: [
      questaoModelo({
        topico: 'Comércio mundial e blocos econômicos',
        ano: null,
        dificuldade: 'medio',
        enunciado: 'O Mercosul, bloco econômico formado majoritariamente por países sul-americanos, tem como membros fundadores:',
        alternativas: [
          { letra: 'A', texto: 'Brasil, Argentina, Paraguai e Uruguai', correta: true },
          { letra: 'B', texto: 'Brasil, Chile, Peru e Colômbia', correta: false },
          { letra: 'C', texto: 'Brasil, México, Argentina e Bolívia', correta: false },
          { letra: 'D', texto: 'Brasil, Venezuela, Equador e Uruguai', correta: false },
        ],
        dica: 'O bloco foi criado pelo Tratado de Assunção em 1991.',
        explicacao: 'Brasil, Argentina, Paraguai e Uruguai são os membros fundadores do Mercosul (1991).',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
      questaoModelo({
        topico: 'Domínios morfoclimáticos do Brasil',
        ano: null,
        dificuldade: 'facil',
        enunciado: 'Cadeias de montanhas como os Andes se formam principalmente devido a qual processo geológico?',
        alternativas: [
          { letra: 'A', texto: 'Erosão eólica', correta: false },
          { letra: 'B', texto: 'Colisão de placas tectônicas', correta: true },
          { letra: 'C', texto: 'Sedimentação fluvial', correta: false },
          { letra: 'D', texto: 'Ação de geleiras', correta: false },
        ],
        dica: 'Pense no encontro de duas placas tectônicas convergentes.',
        explicacao: 'A colisão entre placas tectônicas convergentes dobra e eleva a crosta, formando cadeias montanhosas como os Andes.',
        fonte: 'Modelo autoral no estilo ENEM (não é item oficial do INEP)',
      }),
    ],
  },

  'Redação': {
    aulas: [
      aulaTexto({
        titulo: 'Checklist das 5 competências da redação do ENEM',
        topico: 'As 5 competências da redação (visão geral)',
        resumo: 'Explicação de cada uma das 5 competências avaliadas na redação do ENEM (0-200 pontos cada).',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'ProEnem, artigo com vídeo da Prof. Carol Coelho (verificado 2026-08-19)',
        descricao: 'Artigo do ProEnem detalhando as 5 competências da redação, com referência a vídeo da Prof. Carol Coelho. Fonte: https://enem.proenem.com.br/checklist-das-5-competencias-da-redacao-do-enem-2026/',
      }),
      aulaPendente({
        titulo: 'Competência 1 — norma culta da língua',
        topico: 'Competência 1 — norma culta da língua',
        resumo: 'Domínio da modalidade escrita formal da língua portuguesa.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "competência 1 redação ENEM norma culta aula"',
      }),
      aulaPendente({
        titulo: 'Competência 2 — compreensão do tema',
        topico: 'Competência 2 — compreensão do tema',
        resumo: 'Como evitar fuga ao tema e usar repertório adequado à proposta.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "competência 2 redação ENEM tema aula"',
      }),
      aulaPendente({
        titulo: 'Competência 3 — argumentação',
        topico: 'Competência 3 — argumentação',
        resumo: 'Seleção, organização e interpretação de argumentos.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "competência 3 redação ENEM argumentação aula"',
      }),
      aulaPendente({
        titulo: 'Competência 4 — coesão textual',
        topico: 'Competência 4 — coesão textual',
        resumo: 'Uso de conectivos e mecanismos linguísticos de coesão.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "competência 4 redação ENEM coesão aula"',
      }),
      aulaPendente({
        titulo: 'Competência 5 — proposta de intervenção',
        topico: 'Competência 5 — proposta de intervenção',
        resumo: 'Estrutura agente + ação + meio + finalidade/detalhamento.',
        dificuldade: 'medio',
        mais_cobrado: true,
        fonte: 'buscar: "competência 5 redação ENEM proposta intervenção aula"',
      }),
      aulaPendente({
        titulo: 'Estrutura dissertativo-argumentativa',
        topico: 'Estrutura dissertativo-argumentativa',
        resumo: 'Organização em introdução, desenvolvimento e conclusão.',
        dificuldade: 'basico',
        mais_cobrado: true,
        fonte: 'buscar: "estrutura dissertativo argumentativa ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Repertório sociocultural',
        topico: 'Repertório sociocultural',
        resumo: 'Como usar citações, dados e referências culturais de forma produtiva.',
        dificuldade: 'medio',
        mais_cobrado: false,
        fonte: 'buscar: "repertório sociocultural redação ENEM aula"',
      }),
      aulaPendente({
        titulo: 'Como escrever uma redação do zero',
        topico: 'Como escrever uma redação do zero',
        resumo: 'Vídeo real "Aprenda a escrever uma redação ENEM do zero" (Prof. Carol Coelho), citado no artigo do ProEnem — o link direto do YouTube ainda não foi capturado.',
        dificuldade: 'basico',
        mais_cobrado: false,
        fonte: 'buscar no YouTube: "Aprenda a escrever uma redação ENEM do zero" (Prof. Carol Coelho) — mencionado em https://enem.proenem.com.br',
      }),
      aulaPendente({
        titulo: 'Análise de redações nota 1000',
        topico: 'Análise de redações nota 1000',
        resumo: 'Estudo de casos reais de redações que atingiram a nota máxima.',
        dificuldade: 'dificil',
        mais_cobrado: false,
        fonte: 'buscar: "análise redação nota 1000 ENEM videoaula"',
      }),
    ],
    questoes: [],
  },
};

module.exports = { MATERIAS, TOPICOS, CONTEUDO };
